### ISSUE TITLE
Force torsion weird

### ISSUE THREAD

**Issue by YuriSlayer** [gyoo18/MiniLaboPrototype#31]
```
            //Appliquer la force de torsion avec tout les autres liens //TODO FOrce torsion weird
```

https://github.com/gyoo18/MiniLaboPrototype/blob/3bb501849f77f372b946c424ea2f1f6be8b6d79f/src/com/MiniLabo/prototype/Atome.java#L353

**Comment by gyoo18** [comment]
Réglé le bug
